name: Astro CI

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Lint format and run tests on frontend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.2.4

            - name: Install dependencies
              run: bun install

            - name: Check formatting
              run: bun format:check

            - name: Run a dry build
              run: bun run build
